openapi: 3.0.3
info:
  title: 4V CHEF - OpenAPI 1.0
  description: |-
    API Specification for 4V CHEF
    Manage recipes for 4V Chefs
  termsOfService: http://swagger.io/terms/
  contact:
    email: miguel_goyena@cuatrovientos.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers:
  - url: http://localhost:8000
tags:
  - name: recipes
    description: Everything about Recipes
  - name: recipe-types
    description: Everything about Recipes Types
  - name: nutrients
    description: Everything about Nutrient Types
paths:
  /recipes:
    get:
      tags:
        - recipes
      summary: Retreive the list of receipes
      operationId: searchRecipes
      parameters:
        - in: query
          name: type
          schema:
            type: integer
          description: The ID of the type of recipe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'          
        '400':
          description: Any problem with server
    post:
      tags:
        - recipes
      summary: Add a new recipe
      description: Add a new recipe to the List
      operationId: newRecipe
      requestBody:
        description: New Recipe information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeNew'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Validation Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /recipes/{recipeId}/rating/{rate}:
    post:
      tags:
        - recipes
      summary: add a rating to a recipe
      description: ''
      operationId: uploadRating
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to rate
          required: true
          schema:
            type: integer
            format: int64
        - name: rate
          in: path
          description: Rate, from 0-5 stars
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Validation Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /recipes/{recipeId}:   
    delete:
      tags:
        - recipes
      summary: Delete a recipe
      description: Delete a recipe in 4VChef
      operationId: deleteRecipe
      parameters:
        - name: recipeId
          in: path
          description: Recipe id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Validation Errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /nutrient-types:
    get:
      tags:
        - nutrients
      summary: Retreive the list of current Nutrient Types
      operationId: searchNutrients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NutrientType'          
        '400':
          description: Any problem with server
  /recipe-types:
    get:
      tags:
        - recipe-types
      summary: Retreive the list of current recipe types
      operationId: searchRecipeTypes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeType'          
        '400':
          description: Any problem with server
components:
  schemas:
    Ingredient:
      type: object
      properties:
        name:
          type: string
          example: Sugar
        quantity:
          type: number
          example: 250.50
        unit:
          type: string
          example: gr
    Step:
      type: object
      properties:
        order:
          type: integer
          format: int64
          example: 1
        description:
          type: string
          example: Mix the Eggs with the Suggar 
    NutrientType:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Proteins
        unit:
          type: string
          example: gr
    RecipeType:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: Postre
        description:
          type: string
          example: Para endulzar un buen menú
    Nutrient:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        type:
          $ref: '#/components/schemas/NutrientType'
        quantity:
          type: number
          example: 3.5
    NutrientNew:
      type: object
      properties:
        type-id:
          type: integer
          format: int64
          example: 10
        quantity:
          type: number
          example: 3.5
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: Tiramisu
        number-diner:
          type: integer
          format: int64
          example: 4
        type:
          type: object
          $ref: '#/components/schemas/RecipeType'
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
        nutrients:
          type: array
          items:
            $ref: '#/components/schemas/Nutrient'
        rating:
          $ref: '#/components/schemas/Rating'
    RecipeNew:
      type: object
      properties:
        title:
          type: string
          example: Tiramisu
        number-diner:
          type: integer
          format: int64
          example: 4
        type-id:
          type: integer
          format: int64
          example: 4
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        steps:
          type: array
          items:
            $ref: '#/components/schemas/Step'
        nutrients:
          type: array
          items:
            $ref: '#/components/schemas/NutrientNew'
    Rating:
      type: object
      properties:
        number-votes:
          type: integer
          format: int64
          example: 255
        rating-avg:
          type: number
          example: 4.2
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 21
        description:
          type: string
          example: The name is mandatory